version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: release
          command: npx semantic-release || true
